import Database from 'better-sqlite3';
import path from 'path';
import fs from 'fs';

const DB_PATH = path.join(process.cwd(), 'data', 'aegis.db');

// Persist DB instance across hot reloads in development
const globalDb = globalThis as typeof globalThis & { aegisDb?: Database.Database };

function ensureDataDir() {
  const dir = path.dirname(DB_PATH);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function initializeSchema(db: Database.Database) {
  db.exec(`
    CREATE TABLE IF NOT EXISTS students (
      id          TEXT PRIMARY KEY,
      name        TEXT NOT NULL,
      topic       TEXT NOT NULL,
      goal        TEXT NOT NULL,
      cognitive_dna TEXT NOT NULL DEFAULT '{}',
      created_at  TEXT NOT NULL DEFAULT (datetime('now'))
    );

    CREATE TABLE IF NOT EXISTS concept_nodes (
      id            TEXT PRIMARY KEY,
      student_id    TEXT NOT NULL,
      concept       TEXT NOT NULL,
      mastery       REAL NOT NULL DEFAULT 0.1,
      stability     REAL NOT NULL DEFAULT 2.0,
      last_reviewed TEXT NOT NULL DEFAULT (datetime('now')),
      misconception TEXT NOT NULL DEFAULT '[]',
      review_count  INTEGER NOT NULL DEFAULT 0,
      FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS chat_messages (
      id                TEXT PRIMARY KEY,
      student_id        TEXT NOT NULL,
      role              TEXT NOT NULL CHECK(role IN ('user','assistant')),
      content           TEXT NOT NULL,
      agent_type        TEXT NOT NULL DEFAULT 'PROBE',
      timestamp         TEXT NOT NULL DEFAULT (datetime('now')),
      frustration_level REAL NOT NULL DEFAULT 0.0,
      FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS sessions (
      id               TEXT PRIMARY KEY,
      student_id       TEXT NOT NULL,
      started_at       TEXT NOT NULL DEFAULT (datetime('now')),
      ended_at         TEXT,
      concepts_covered TEXT NOT NULL DEFAULT '[]',
      mastery_delta    REAL NOT NULL DEFAULT 0.0,
      FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS idx_concepts_student ON concept_nodes(student_id);
    CREATE INDEX IF NOT EXISTS idx_messages_student ON chat_messages(student_id, timestamp);
    CREATE INDEX IF NOT EXISTS idx_sessions_student ON sessions(student_id);

    -- Always-on persistent cognitive model (one row per student, upserted)
    CREATE TABLE IF NOT EXISTS cognitive_state (
      student_id              TEXT PRIMARY KEY,
      long_term_understanding TEXT NOT NULL DEFAULT '{}',
      misconception_history   TEXT NOT NULL DEFAULT '[]',
      learning_patterns       TEXT NOT NULL DEFAULT '{}',
      dna_evolution           TEXT NOT NULL DEFAULT '[]',
      tom_accuracy_trend      TEXT NOT NULL DEFAULT '[]',
      teaching_weights        TEXT NOT NULL DEFAULT '{}',
      pending_tom_prediction  TEXT,
      last_updated            TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
    );

    -- Compressed long-term memory snapshots
    CREATE TABLE IF NOT EXISTS memory_snapshots (
      id            TEXT PRIMARY KEY,
      student_id    TEXT NOT NULL,
      created_at    TEXT NOT NULL DEFAULT (datetime('now')),
      summary       TEXT NOT NULL DEFAULT '{}',
      message_count INTEGER NOT NULL DEFAULT 0,
      keywords      TEXT NOT NULL DEFAULT '[]',
      FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS idx_cognitive_state ON cognitive_state(student_id);
    CREATE INDEX IF NOT EXISTS idx_memory_snapshots ON memory_snapshots(student_id, created_at);

    -- Global concept difficulty insights (aggregated across all students)
    CREATE TABLE IF NOT EXISTS concept_difficulty (
      concept                  TEXT PRIMARY KEY,
      avg_attempts_to_master   REAL NOT NULL DEFAULT 1.0,
      misconception_frequency  REAL NOT NULL DEFAULT 0.0,
      common_misconceptions    TEXT NOT NULL DEFAULT '[]',
      total_students           INTEGER NOT NULL DEFAULT 0,
      last_updated             TEXT NOT NULL DEFAULT (datetime('now'))
    );

    -- Learning plans generated by session-end analysis
    CREATE TABLE IF NOT EXISTS learning_plans (
      id           TEXT PRIMARY KEY,
      student_id   TEXT NOT NULL,
      created_at   TEXT NOT NULL DEFAULT (datetime('now')),
      plan         TEXT NOT NULL DEFAULT '[]',
      status       TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'completed', 'superseded')),
      FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
    );

    -- Prompt performance tracking for self-improving prompts
    CREATE TABLE IF NOT EXISTS prompt_performance (
      id              TEXT PRIMARY KEY,
      student_id      TEXT NOT NULL,
      agent_type      TEXT NOT NULL,
      timestamp       TEXT NOT NULL DEFAULT (datetime('now')),
      mastery_delta   REAL NOT NULL DEFAULT 0.0,
      frustration_end REAL NOT NULL DEFAULT 0.0,
      reflection_score REAL NOT NULL DEFAULT 0.0,
      tom_accuracy    REAL,
      FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS idx_concept_difficulty ON concept_difficulty(concept);
    CREATE INDEX IF NOT EXISTS idx_learning_plans ON learning_plans(student_id, status);
    CREATE INDEX IF NOT EXISTS idx_prompt_performance ON prompt_performance(student_id, agent_type);

    -- ── AGI Upgrade Tables ────────────────────────────────────────────────────

    -- Tutor self-model (single global row — the tutor learns who it is as a teacher)
    CREATE TABLE IF NOT EXISTS tutor_profile (
      id                          TEXT PRIMARY KEY DEFAULT 'global',
      agent_success_rates         TEXT NOT NULL DEFAULT '{}',
      preferred_explanation_styles TEXT NOT NULL DEFAULT '{}',
      teaching_wisdom             TEXT NOT NULL DEFAULT '[]',
      total_students_taught       INTEGER NOT NULL DEFAULT 0,
      total_sessions              INTEGER NOT NULL DEFAULT 0,
      avg_mastery_improvement     REAL NOT NULL DEFAULT 0.0,
      last_updated                TEXT NOT NULL DEFAULT (datetime('now'))
    );

    -- Autonomous task queue (AEGIS acts without user prompt)
    CREATE TABLE IF NOT EXISTS autonomous_tasks (
      id            TEXT PRIMARY KEY,
      student_id    TEXT NOT NULL,
      type          TEXT NOT NULL,
      priority      INTEGER NOT NULL DEFAULT 5,
      scheduled_for TEXT NOT NULL DEFAULT (datetime('now')),
      status        TEXT NOT NULL DEFAULT 'pending',
      payload       TEXT NOT NULL DEFAULT '{}',
      created_at    TEXT NOT NULL DEFAULT (datetime('now')),
      delivered_at  TEXT,
      FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS idx_autonomous_tasks ON autonomous_tasks(student_id, status);

    -- Cross-student curriculum intelligence
    CREATE TABLE IF NOT EXISTS curriculum_insights (
      id            TEXT PRIMARY KEY,
      insight_type  TEXT NOT NULL,
      concept       TEXT,
      data          TEXT NOT NULL DEFAULT '{}',
      student_count INTEGER NOT NULL DEFAULT 0,
      confidence    REAL NOT NULL DEFAULT 0.0,
      generated_at  TEXT NOT NULL DEFAULT (datetime('now'))
    );

    CREATE INDEX IF NOT EXISTS idx_curriculum_insights ON curriculum_insights(concept, insight_type);

    -- Functional emotion state (per student — tutor's emotional model of each student)
    CREATE TABLE IF NOT EXISTS emotion_state (
      student_id   TEXT PRIMARY KEY,
      concern      REAL NOT NULL DEFAULT 0.3,
      curiosity    REAL NOT NULL DEFAULT 0.5,
      confidence   REAL NOT NULL DEFAULT 0.5,
      last_updated TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
    );
  `);

  // Run safe migrations for new columns (ALTER TABLE IF NOT EXISTS column doesn't exist in SQLite)
  const migrations = [
    `ALTER TABLE concept_nodes ADD COLUMN feynman_clarity REAL`,
    `ALTER TABLE concept_nodes ADD COLUMN feynman_depth REAL`,
    `ALTER TABLE chat_messages ADD COLUMN reflection_score REAL`,
    `ALTER TABLE chat_messages ADD COLUMN tom_score REAL`,
  ];
  for (const migration of migrations) {
    try {
      db.exec(migration);
    } catch {
      // Column already exists — safe to ignore
    }
  }

  console.log('[AEGIS] Database schema verified / updated successfully');
}

export function getDb(): Database.Database {
  if (!globalDb.aegisDb) {
    ensureDataDir();
    const db = new Database(DB_PATH);
    db.pragma('journal_mode = WAL');
    db.pragma('foreign_keys = ON');
    initializeSchema(db);
    globalDb.aegisDb = db;
  }
  return globalDb.aegisDb;
}

// Typed query helpers
export function getStudent(id: string) {
  const db = getDb();
  const row = db.prepare('SELECT * FROM students WHERE id = ?').get(id) as Record<string, unknown> | undefined;
  if (!row) return null;
  return {
    ...row,
    cognitive_dna: typeof row.cognitive_dna === 'string' ? JSON.parse(row.cognitive_dna) : row.cognitive_dna,
  };
}

export function getConceptNodes(studentId: string) {
  const db = getDb();
  const rows = db.prepare('SELECT * FROM concept_nodes WHERE student_id = ? ORDER BY mastery ASC').all(studentId) as Record<string, unknown>[];
  return rows.map(row => ({
    ...row,
    misconception: typeof row.misconception === 'string' ? JSON.parse(row.misconception) : row.misconception,
  }));
}

export function getChatHistory(studentId: string, limit = 20) {
  const db = getDb();
  return db.prepare(
    'SELECT * FROM chat_messages WHERE student_id = ? ORDER BY timestamp DESC LIMIT ?'
  ).all(studentId, limit) as Record<string, unknown>[];
}

export function upsertConceptNode(data: {
  id: string;
  student_id: string;
  concept: string;
  mastery: number;
  stability: number;
  last_reviewed: string;
  misconception: unknown[];
  review_count: number;
}) {
  const db = getDb();
  db.prepare(`
    INSERT INTO concept_nodes (id, student_id, concept, mastery, stability, last_reviewed, misconception, review_count)
    VALUES (@id, @student_id, @concept, @mastery, @stability, @last_reviewed, @misconception, @review_count)
    ON CONFLICT(id) DO UPDATE SET
      mastery       = excluded.mastery,
      stability     = excluded.stability,
      last_reviewed = excluded.last_reviewed,
      misconception = excluded.misconception,
      review_count  = excluded.review_count
  `).run({ ...data, misconception: JSON.stringify(data.misconception) });
}

export function insertMessage(data: {
  id: string;
  student_id: string;
  role: string;
  content: string;
  agent_type: string;
  timestamp: string;
  frustration_level: number;
}) {
  const db = getDb();
  db.prepare(`
    INSERT INTO chat_messages (id, student_id, role, content, agent_type, timestamp, frustration_level)
    VALUES (@id, @student_id, @role, @content, @agent_type, @timestamp, @frustration_level)
  `).run(data);
}

export function updateStudentDNA(studentId: string, dna: unknown) {
  const db = getDb();
  db.prepare('UPDATE students SET cognitive_dna = ? WHERE id = ?').run(JSON.stringify(dna), studentId);
}
